language: rust
os:
  - linux
  # - windows
  # - osx
rust: 
  - nightly
  # - beta
  # - stable
cache: cargo

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
before_script:
#        - cargo install grcov # failing, install from tarball
  - rustup component add llvm-tools-preview
script:
  - export CARGO_INCREMENTAL=0 &&
    export RUSTFLAGS="-Zinstrument-coverage" &&
    export LLVM_PROFILE_FILE="your_name-%p-%m.profraw" &&
    export RUSTDOCFLAGS="-Cpanic=abort" &&
    cargo test --verbose
  - export RUST_BACKTRACE=1 && cargo doc --no-deps --verbose
  - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info # from https://crates.io/crates/grcov/0.5.13#grcov-with-travis
  - bash <(curl -s https://codecov.io/bash) -f lcov.info