language: rust
os:
  - linux
  - windows
  - mac
rust: 
  - nightly
  - beta
  - stable
cache: cargo
fast_finish: true
allow_failures: 
  - nightly
include:
      script: |
        export RUST_BACKTRACE=1 &&
        cargo build --verbose &&
        cargo test --verbose &&  
        cargo doc --no-deps --verbose

jobs:
  include:
    - name: Coverage
    - env: NAME='cargo-travis'
      sudo: required # travis-ci/travis-ci#9061
      before_script:
        - cargo install grcov || echo "grcov already installed" 
        - rustup component add llvm-tools-preview
      script: |
        export CARGO_INCREMENTAL=0 &&
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort" &&
        export RUSTDOCFLAGS="-Cpanic=abort" &&
        cargo test --verbose &&  
        grcov . -s . --binary-path ./target/debug/ -t coveralls --branch --ignore-not-existing --token YW0qzuKwPIUbh67GzMIlbdHnljDbHFBS9 > coveralls.json &&
        bash <(curl -s https://codecov.io/bash) -s coveralls.json

#          grcov . -s . --binary-path ./target/debug/ -t coveralls --token YW0qzuKwPIUbh67GzMIlbdHnljDbHFBS9 > coveralls.json &&
